version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      KAFKA_OPTS: "-Dzookeeper.authProvider.1=org.apache.zookeeper.server.auth.SASLAuthenticationProvider -Djava.security.auth.login.config=/opt/security/zookeeper-server.jaas"
      ZOOKEEPER_AUTH_PROVIDER_1: org.apache.zookeeper.server.auth.SASLAuthenticationProvider
      ZOOKEEPER_REQUIRE_CLIENT_SASL_AUTH: "true"   
    ports:
      - 2181:2181
    volumes:
      - ./zookeeper-server.jaas:/opt/security/zookeeper-server.jaas
    networks:
      - kafka

  broker:
    image: confluentinc/cp-kafka:7.3.0
    ports:
      - 9092:9092
      - 9094:9094
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'SASL_PLAINTEXT:SASL_PLAINTEXT,SASL_EXTERNAL:SASL_PLAINTEXT'
      KAFKA_ADVERTISED_LISTENERS: 'SASL_PLAINTEXT://broker:9092,SASL_EXTERNAL://localhost:9094'
      KAFKA_LISTENERS: 'SASL_PLAINTEXT://0.0.0.0:9092,SASL_EXTERNAL://:9094'
      #KAFKA_SASL_MECHANISMS: SCRAM-SHA-256
      KAFKA_SASL_ENABLED_MECHANISMS: SCRAM-SHA-256
      KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: SCRAM-SHA-256
      KAFKA_SECURITY_INTER_BROKER_PROTOCOL: SASL_PLAINTEXT
      KAFKA_AUTHORIZER_CLASS_NAME: kafka.security.authorizer.AclAuthorizer
      KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND: "false"
      KAFKA_SUPER_USERS: User:admin;User:redpanda
      KAFKA_OPTS: -Djava.security.auth.login.config=/etc/kafka/jaas/kafka_server.conf
      KAFKA_ZOOKEEPER_SET_ACL: "true"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - ./kafka_server.conf:/etc/kafka/jaas/kafka_server.conf
      - ./adminclient-configs.conf:/etc/kafka/jaas/adminclient-configs.conf
    depends_on:
      - zookeeper
    networks:
      - kafka

  zookeeper-add-kafka-users:
    image: confluentinc/cp-kafka:7.3.0
    environment:
      KAFKA_BROKER_ID: ignored
      KAFKA_ZOOKEEPER_CONNECT: ignored
      KAFKA_OPTS: -Djava.security.auth.login.config=/etc/kafka/secrets/zookeeper_client_jaas.conf
    volumes:
      - ./zookeeper_client_jaas.conf:/etc/kafka/secrets/zookeeper_client_jaas.conf
    depends_on:
      - zookeeper
    command: "bash -c 'echo Waiting for Zookeeper to be ready... && \
                          cub zk-ready zookeeper:2181 120 && \
                          kafka-configs --zookeeper zookeeper:2181 --alter --add-config 'SCRAM-SHA-256=[password=redpandasecret123]' --entity-type users --entity-name redpanda && \
                          kafka-configs --zookeeper zookeeper:2181 --alter --add-config 'SCRAM-SHA-256=[password=admin-secret]' --entity-type users --entity-name admin '"
    networks:
      - kafka      

  kafka-ui:
    image: provectuslabs/kafka-ui:v0.6.2
    depends_on:
      - broker
    environment:
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: broker:9092
      KAFKA_CLUSTERS_0_PROPERTIES_SECURITY_PROTOCOL: SASL_PLAINTEXT
      KAFKA_CLUSTERS_0_PROPERTIES_SASL_MECHANISM: SCRAM-SHA-256
      KAFKA_CLUSTERS_0_PROPERTIES_SASL_JAAS_CONFIG: 'org.apache.kafka.common.security.scram.ScramLoginModule required username="redpanda" password="redpandasecret123";'
      DYNAMIC_CONFIG_ENABLED: "true"
    networks:
      - kafka
    ports:
      - 8080:8080

networks:
  kafka:
    name: kafka